image: docker

services:
  - docker:dind

variables:
  TEST_IMAGE: registry.gitlab.com/kane-c/react-init:$CI_BUILD_REF_NAME
  RELEASE_IMAGE: registry.gitlab.com/kane-c/react-init:$CI_BUILD_TAG

before_script:
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com

build:
  stage: build
  script:
    - docker build --pull -t $TEST_IMAGE .
    - docker push $TEST_IMAGE

test:
  stage: test
  script:
    - docker pull $TEST_IMAGE
    - docker run $TEST_IMAGE npm test

release-image:
  stage: deploy
  script:
    - docker pull $TEST_IMAGE
    - docker tag $TEST_IMAGE $RELEASE_IMAGE
    - docker push $RELEASE_IMAGE
  only:
    - master

deploy:
  stage: deploy
  script:
    - docker pull $RELEASE_IMAGE
    - docker run $RELEASE_IMAGE npm run deploy
  environment: production
  when: manual
