language: node_js
node_js:
  - "node"
  - "6"
before_script:
  - npm run lint
  # TODO Add Flow when ready
after_success:
  - npm install coveralls
  - 'cat ./coverage/lcov.info | ./node_modules/.bin/coveralls'
