version: '3'
services:
  app:
    build:
      context: '.'
      dockerfile: Dockerfile-dev
    environment:
      NODE_ENV: 'development'
    ports:
      - '8080:8080'
      - '8081:8081' # Storybook
    volumes:
      - '.:/app'
