FROM node:8-alpine

CMD ["npm", "start"]
EXPOSE 8080
WORKDIR /app

ENV \
  # The official Docker image sets this to `info` which is far too verbose
  NPM_CONFIG_LOGLEVEL=warn \
  NODE_ENV=production \
  PATH="/app/node_modules/.bin:${PATH}"

# git is required for the pre-commit hook
RUN apk add --no-cache git

# Need to run as non-root to be able to `npm install` without error with
# mounted volumes
USER node
